### PR TITLE
fix: wait namespace is actually deleted (#413)

### PR DESCRIPTION
**Pull request by kensipe**
Originally on https://github.com/kudobuilder/kuttl/pull/413 was merged and caused failures.   We have issues with contributor PR being tested on circle ci.  This is the same PR.   The squashed commit was reverted and this PR is a cherry-pick of that commit

Co-authored-by: Erik Godding Boye <egboye@gmail.com>
Signed-off-by: Charles-Edouard Brétéché <charles.edouard@nirmata.com>

**What this PR does / why we need it**:

Fixes #

### CODE REVIEW

**Comment by chipzoller** [comment]
How can we help here? Without this fix it's is causing test failures on our side. See https://github.com/kyverno/kyverno/pull/5413.

**Comment by eddycharly** [comment]
@chipzoller im waiting for the CI PR to merge so that I can investigate better.

**Comment by eddycharly** [comment]
This one https://github.com/kudobuilder/kuttl/pull/337
cc @kensipe

**Comment by eddycharly** [comment]
I wonder if this happens because k8s components are not deployed in the cluster, therefore namespace finalizers are never processed.

**Comment by kensipe** [comment]
yeah... the integration-tests are just against etcd and api-server (no controllers).   We will need to look into a solution around that.   The e2e tests should be against a kind cluster but don't appear to be... need to look into why on that as well.   I really like this PR and will work to work it in.

**Comment by kensipe** [comment]
@eddycharly as suspected... when running against testenv, we can't delete namespaces and need to skip-delete.  Testing all looked good.  plan to merge after CI.  Thanks for this great work!

**Pull request merged**
