### PR TITLE
feat: add full name support for test case name

### LINKED ISSUE #403: [Enhancement] Output test case full path in final report
**What would you like to be added**:

Along with the result of the test (`PASS` | `FAIL`), print the full path to the test case if known through a TestSuite file.

**Why is this needed**:

With hundreds of possible tests being executed across a complex hierarchy of directories, knowing which test failed only by the name of the test case (i.e., the parent folder holding the kuttl test files) isn't often enough. For example, something like this is printed today:

```
        --- PASS: kuttl/harness/external-metrics (25.87s)
        --- PASS: kuttl/harness/nomutateDigest-verifyDigest-norequired (5.38s)
        --- PASS: kuttl/harness/mutateDigest-noverifyDigest-norequired (3.30s)
        --- PASS: kuttl/harness/keyless-nomutatedigest-noverifydigest-required (3.92s)
```

In reality, each of those test cases are six directories deep, and they may not all even be in the same parent directory.

This enhancement is to print, in the final report output, the full path to the test cases as known based upon the TestSuite file.

### PR DESCRIPTION
**Pull request by eddycharly**
**What this PR does / why we need it**:

This PR adds support for full folder path in the test name (instead of the shorter folder name).
This is useful when test cases are organised in deep folder hierarchy.

Fixes #403

cc @chipzoller

### CODE REVIEW

**Comment by chipzoller** [comment]
Closes #403

**Comment by kensipe** [comment]
this is interesting...   First thought that comes to mind is we support testsuites and tests that come from a tarball.   The tarballs are expanded into a system temp folder I believe.  This could make for a not so friendly full name.   It would be good to see in the PR a sample current and change output (abbrev with just the affected output).   I will look to do that now.

**Comment by kensipe** [comment]
looks like expected output is in the issue... thank you!

**Comment by kensipe** [comment]
focusing a conversation on the issue #403  instead of this PR

**Pull request closed without merging**
