### PR TITLE
Add CI using Dispatch

### PR DESCRIPTION
**Pull request by jbarrick-mesosphere**

### CODE REVIEW

**Comment by gerred** [comment]
@jbarrick-mesosphere Is this a public instance of Dispatch, of which the license is donated for use by the KUDO and kuttl project? If that is true, can you additionally add this to the README to make it clear?

**Comment by jbarrick-mesosphere** [comment]
It's not, but it can be if we have a cluster. Do we have a cluster I can use?

**Comment by gerred** [comment]
@runyontr and I are working on infrastructure tomorrow under the kudobuilder/infrastructure repo and this will be divested infrastructure for use by the KUDO project -- so yes.

**Comment by jbarrick-mesosphere** [comment]
Sounds great! Let's use that once it's ready and keep this paused.

**Comment by gerred** [comment]
What do you need req/limit wise on a GKE node?

**Comment by jbarrick-mesosphere** [comment]
Fairly low, since these are just go builds / tests. 2gb 2CPU is probably plenty.

**Comment by jbarrick-mesosphere** [comment]
That is, until we add KIND e2e tests. Those we tend to run with 16GB and 4CPUs.

**Comment by gerred** [comment]
could we make a service account so that a dispatch job could spin those up as preemptible to keep costs low?

**Comment by jbarrick-mesosphere** [comment]
The pods get started dynamically, so we could use a cluster autoscaler to scale a preemptimble node pool?

**Comment by gerred** [comment]
i like that. we might not have time to integrate that tomorrow but i'll throw CA in there

**Comment by jbarrick-mesosphere** [comment]
```
Add CI using Dispatch
Name:           kudobuilder-kuttl-justin-74ea12c-gxk4v
Namespace:      dispatch
Pipeline Ref:   kudobuilder-kuttl-justin-74ea12c-gxk4v

Status
STARTED        DURATION   STATUS
1 minute ago   1 minute   Succeeded

Resources
NAME                  RESOURCE REF
kuttl-git             kuttl-git-wh2hr
kubectl-kuttl-build   kubectl-kuttl-build-zw259
kubebuilder           kubebuilder-tltcw
kuttl-test            kuttl-test-fzgkv

Params
No params

Taskruns
NAME                                                              TASK NAME             STARTED          DURATION     STATUS
kudobuilder-kuttl-justin-74ea12c-gxk4v-integration-test-2mltl     integration-test      31 seconds ago   28 seconds   Succeeded
kudobuilder-kuttl-justin-74ea12c-gxk4v-fetch-kubebuilder-ls5xr    fetch-kubebuilder     1 minute ago     25 seconds   Succeeded
kudobuilder-kuttl-justin-74ea12c-gxk4v-kubectl-kuttl-buil-5zb2k   kubectl-kuttl-build   1 minute ago     46 seconds   Succeeded
kudobuilder-kuttl-justin-74ea12c-gxk4v-kuttl-test-lr77c           kuttl-test            1 minute ago     36 seconds   Succeeded
kudobuilder-kuttl-justin-74ea12c-gxk4v-lint-mzddl                 lint                  1 minute ago     36 seconds   Succeeded
```

**Comment by kensipe** [comment]
merged with master to handle conflicts

**Pull request closed without merging**
