### PR TITLE
chore: move to kyverno/kuttl

### PR DESCRIPTION
**Pull request by eddycharly**
This PR moves to `kyverno/kuttl`.

### CODE REVIEW

**Comment by erikgb** [comment]
@eddycharly Does this mean Kyverno is moving to a more permanent fork of kuttl? I hope we can sort this out over time! WDYT about moving kuttl out of kudobuilder? The kudobuilder ecosystem seems quite abandoned. WDYT @kensipe

**Comment by eddycharly** [comment]
@erikgb I hope we can continue to contribute to kuttl but for now we need to move forward so we decided to go with a fork.

**Comment by erikgb** [comment]
> @erikgb I hope we can continue to contribute to kuttl but for now we need to move forward so we decided to go with a fork.

I totally understand the why, but hope we can "join forces" for the future.

**Comment by eddycharly** [comment]
Definitely, if you have suggestions to make contributing easier let us know. Currently, the lack of maintainers make it difficult to propose changes, get feedback, etc...

**Pull request closed without merging**
